/*
 * Popinz Endpoints
 * Popinz dev endpoints API V 0.0.3 - Courses are renamed CourseEvents - Users are renamed Persons - Add subjects CRUD - Add groups CRUD - Add filter abilities list of objects - not implemented are prefixed (N/I) - CourseEvent startDate and endDate renamed as startDatetime and endDatetime V 0.0.4 - make startDatetime and endDatetime required in list query - precise datetime as ISO 8601 V 0.0.5 - remove /list suffix for getting array of objects V 0.0.6  work in progress - make GET / POST / PUT / DELETE on one or more objects - add filter on each GET - remove single  GET / POST / PUT / DELETE operations v 0.0.7  todo  -add pagination - add pagination to all GET operation - 200 for GET - 201 for created - 204 for deleted - https://tools.ietf.org/html/rfc5789  PATCH for partial - add single  GET / PATCH / DELETE operations 200 GET / 204 PATCH OR DELETE - http://www.restapitutorial.com/lessons/httpmethods.html
 *
 * OpenAPI spec version: 0.0.5
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mday.event;


import java.util.Date;

/**
 * CourseEvent
 */
public class CourseEvent {

    private String nameEvent;

    private Date startDatetime;

    private Date endDatetime;

    private String room;
    private String address;

    public CourseEvent(String nameEvent, Date startDatetime, Date endDatetime, String room, String address) {
        this.nameEvent = nameEvent;
        this.startDatetime = startDatetime;
        this.endDatetime = endDatetime;
        this.room = room;
        this.address = address;
    }

    public String getNameEvent() {
        return nameEvent;
    }

    public void setNameEvent(String nameEvent) {
        this.nameEvent = nameEvent;
    }

    public Date getStartDatetime() {
        return startDatetime;
    }

    public void setStartDatetime(Date startDatetime) {
        this.startDatetime = startDatetime;
    }

    public Date getEndDatetime() {
        return endDatetime;
    }

    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    public String getRoom() {
        return room;
    }

    public void setRoom(String room) {
        this.room = room;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
}

